FROM alpine/openclaw:latest
RUN install -d -m 700 /home/node/.ssh
ADD files/gateway-entrypoint.sh /entrypoint.sh
ADD files/openclaw.json /openclaw.json.default
ENTRYPOINT ["/entrypoint.sh"]
CMD ["node", "dist/index.js", "gateway", "--bind", "lan", "--port", "18789"]
